name: Bundle and send to release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.1.25

    - name: Install dependencies
      run: |
        NODE_ENV=production bun install

    - name: Checkout release branch
      run: |
        git fetch origin
        git checkout release || git checkout -b release origin/release

    - name: Merge main into release
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git merge origin/main --no-edit --allow-unrelated-histories --strategy-option theirs || true

    - name: Bundle assets
      run: bun run --run build

    - name: Add and commit bundled files
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add -f dist/  # Add the bundled files even if they're gitignored
        git commit -m "Bundled code from main commit $(git rev-parse --short HEAD)" || echo "No changes to commit"

    - name: Push changes to release branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin release