name: Bundle and send to release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.1.25

    - name: Install dependencies
      run: |
        NODE_ENV=production bun install

    - name: Bundle assets
      run: bun run --run build

    # Step 4: Checkout the release branch
    - name: Checkout release branch
      run: |
        git fetch origin release
        git checkout release || git checkout -b release

    # Step 5: Commit the bundled files to the release branch
    - name: Commit bundled files to release branch
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add -f dist/  # Force add the dist/ directory
        git commit -m "Bundled code from master commit $(git rev-parse --short HEAD)" || echo "No changes to commit"
        git push origin release