name: Create Release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.1.25

    - name: Install dependencies
      run: |
        NODE_ENV=production bun install

    - name: Bundle assets
      run: bun run --run build

    - name: Get version from package.json
      id: get_version
      run: |
        VERSION=$(echo "console.log(require('./package.json').version)" | bun run -)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v${{ env.VERSION }}"
        release_name: "Release ${{ env.VERSION }}"
  
    - name: Upload dist/index.js to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/index.js
        asset_name: index.js
        asset_content_type: application/javascript