name: Create Release

on:
  push:
    branches:
      - release

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          ref: release
          fetch-depth: 0

      - name: Reset release branch to main
        run: |
          git fetch origin main
          git checkout -B release origin/main

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.25

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(echo "console.log(require('./package.json').version)" | bun run -)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ env.VERSION }}"
          release_name: "Release ${{ env.VERSION }}"